Repository nanoframework/System.IO.Ports, pull requests merged in 2022-05, with the labels that each got.

#84 Align default newline with .NET
  README.md
  System.IO.Ports/SerialPort.cs
  Tests/UnitTestsSerialPort/README.md
  Tests/UnitTestsSerialPort/SerialTests.cs
Labels: Breaking-Change, Type: enhancement

#85 Improve Readme
  README.md
Labels: Type: Documentation

#83 Improve intellisense comment for watchchar event
  README.md
  System.IO.Ports/SerialData.cs
Labels: Type: Documentation

#86 Add WriteByte to SerialPort
  System.IO.Ports/Properties/AssemblyInfo.cs
  System.IO.Ports/SerialPort.cs
  version.json
Labels: Type: enhancement

#87 Fix ReceivedBytesThreshold
  System.IO.Ports/Properties/AssemblyInfo.cs
  System.IO.Ports/SerialPort.cs
  version.json
Labels: Type: bug
